### ISSUE TITLE
ShineWifi-F + SFP-5000US/ES Almost working...

### ISSUE THREAD

**Issue by JohnGalt1717** [WilbertVerhoeff/Growatt#1]
This mostly works:

```
output:
# Blue Led
  - id: light_bl
    platform: gpio
    pin: 16
# Green Led
  - id: light_gr
    platform: gpio
    pin: 0
# Red Led
  - id: light_rd
    platform: gpio
    pin: 2
    
uart:
  - id: uart1
    baud_rate: 9600
    tx_pin: GPIO1
    rx_pin: GPIO3

modbus:
  uart_id: uart1
  flow_control_pin: GPIO4

sensor:
  - platform: growatt_solar
    update_interval: 10s

    inverter_status:
      name: "${device_name} Status Code"

    phase_c:
      voltage:
          name: "${device_name} AC Voltage"
      current:
          name: "${device_name} AC Current"
          filters:
            - multiply: 0.001
      active_power:
          name: "${device_name} AC Power"

    pv1:
      voltage:
          name: "${device_name} PV Voltage"
      current:
          name: "${device_name} PV Current"
          filters:
            - multiply: 0.1
      active_power:
          name: "${device_name} PV Active Power"

    active_power:
      name: "${device_name} Grid Active Power"

    pv_active_power:
      name: "${device_name} PV Active Power"

    frequency:
      name: "${device_name} Frequency"

    energy_production_day:
      name: "${device_name} Today's Generation"
      filters:
        - multiply: 0.00001

```

And I can get similar with the Wifi-S on this repo and putting in the multipliers, but the PV Active Power, Voltage, AC Frequency are all 0. Any suggestions on how to get those working?
