### ISSUE TITLE
devicename not declared in the X code and update interval 60 sec.

### ISSUE THREAD

**Issue by Pooyan31** [WilbertVerhoeff/Growatt#4]
I have flashed the code succesfully on the shine-wifi X stick, 2 things i noticed in Home Assistant;

1. The sensors in HA dashboard display "**$(devicename)** Ac Frequency etc. so i presume the code **name: ${device_name}** and **device_name: is** missing?
2. The update of the sensors is 60 sec. i read somewhere that 5 sec is possible also?

HA version 2023.4.1
Growatt MIC 3000 X

**Comment by RudolfRendier** [comment]
1. I noticed the same thing. I'll propose some minor fixes in a PR. (Hardware will arrive soon)
2. That is probably a setting for the controller, as described here:

https://esphome.io/components/modbus_controller.html

I think it should look like this:
```
modbus_controller:
  - id: growatt
# the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 5
```

Not sure if that makes sense for the device or even works.
